### PR TITLE
#2 fix

### PR DESCRIPTION
**Pull request by kwolfy**
I fixed the #2 issue. I added this lines in mouseUp listeners

```
event.preventDefault();
event.stopPropagation();
```

### CODE REVIEW

**Comment by bupy7** [comment]
I have not exists #76 issue.

**Comment by kwolfy** [comment]
Sorry, i mixed up two jquery-cropbox plugins and aded issue in another.
That's it 
_if you use any js script which using "mouseup" event it's not working because jquery-cropbox stops every mouseup event after itself_

**Comment by kwolfy** [comment]
Look, I created example where cropbox breaks down jcrop plugin http://jsfiddle.net/xygcb4Lh/
Try to use jcrop

**Comment by bupy7** [comment]
@kwolfy ok! you can replace commit files at only with this fix bug without other fixed? what you sent me it contains many fix a type space, indents and etc. it would be great if you send me commit files only with this bug fix.

**Comment by kwolfy** [comment]
Ok, of course i will do that

**Comment by bupy7** [comment]
@kwolfy only this fix. one pull-request at one bug.

**Pull request closed without merging**
